### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by artfulhacker** [DejanPelzel/statuscake.client#6]
repo appears to be missing the following files:

Error   1   Source file 'Models\AuthDetails.cs' could not be found
Error   2   Source file 'Models\CheckResult.cs' could not be found
Error   3   Source file 'Models\ContactGroup.cs' could not be found
Error   4   Source file 'Models\DeleteTest.cs' could not be found
Error   5   Source file 'Models\TestDetails.cs' could not be found

**Comment by DejanPelzel** [comment]
Oh wow, I'm so clumsy... I forgot to add untracked files. Thank you... I just submitted them. Sorry for being a bit slow, didn't see the issue before.
